export const FETCH_TREE = 'FETCH_TREE';
export const SET_TREE = 'SET_TREE';

export const OPEN_CLOSE_FOLDER = 'OPEN_CLOSE_FOLDER';
export const SELECT_FOLDER = 'SELECT_FOLDER';

export const CHANGING_DATA = 'CHANGING_DATA';
export const DELETE_FROM_TREE = 'DELETE_FROM_TREE';

export const RESTORING_DATA_MAIN_ROUTE = 'RESTORING_DATA_MAIN_ROUTE';
export const SET_PATH = 'SET_PATH';
export const RESTORING_DATA_SECOND_ROUTE = 'RESTORING_DATA_SECOND_ROUTE';
export const SET_SELECTED_FOLDER = 'SET_SELECTED_FOLDER';

export const ADD_TO_SELECTED_FOLDER = 'ADD_TO_SELECTED_FOLDER';
export const UPDATE_SELECTED_FOLDER = 'UPDATE_SELECTED_FOLDER';
export const DELETE_FROM_SELECTED_FOLDER = 'DELETE_FROM_SELECTED_FOLDER';

export const CREATE_FOLDER = 'CREATE_FOLDER';
export const UPDATE_FOLDER = 'UPDATE_FOLDER';
export const DELETE_FOLDER = 'DELETE_FOLDER';

export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPDATE_FILE = 'UPDATE_FILE';
export const DELETE_FILE = 'DELETE_FILE';